version: '3'
services:
  app:
    image: graduation-project-gulistanboylu:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo/tinytale
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
