version: '3'
services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo/tinytale
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app/src

  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
