version: '3'
services:
  app:
    image: graduation-project-gulistanboylu:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
      - MONGODB_DATABASE
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
